name: Deploy APP1

on:
  push:
    branches:
      - master
    paths:
      - "apps/app1/**"
      - "docker/app1.Dockerfile"
      - ".github/workflows/app1.yaml"
  workflow_dispatch:

jobs:
  deploy-app1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name acrforksdemo1

    - name: Build & Push APP1
      run: |
        docker build -f docker/app1.Dockerfile \
          -t acrforksdemo1.azurecr.io/app1:${{ github.sha }} .
        docker push acrforksdemo1.azurecr.io/app1:${{ github.sha }}

    - name: Deploy APP1
      run: |
        az aks get-credentials \
          --resource-group AKSMM_group \
          --name AKSMM \
          --overwrite-existing

        kubectl set image deployment/app1 \
          app1=acrforksdemo1.azurecr.io/app1:${{ github.sha }}

        kubectl rollout status deployment/app1
