name: Deploy APP1 (DEV)

on:
  push:
    branches:
      - master
    paths:
      - "apps/app1/**"
      - "docker/Dockerfile.app1"
      - "helm-app1/**"
      - ".github/workflows/app1.yaml"

  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  deploy-app1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name acrforksdemo1

    - name: Build & Push APP1
      run: |
        docker build \
          -f docker/Dockerfile.app1 \
          -t acrforksdemo1.azurecr.io/app1:${IMAGE_TAG} \
          -t acrforksdemo1.azurecr.io/app1:latest \
          .

        docker push acrforksdemo1.azurecr.io/app1:${IMAGE_TAG}
        docker push acrforksdemo1.azurecr.io/app1:latest

    - name: Deploy APP1 to AKS (DEV)
      run: |
        az aks get-credentials \
          --resource-group AKSMM_group \
          --name AKSMM \
          --overwrite-existing

        kubectl set image deployment/dev-app1 \
          app1=acrforksdemo1.azurecr.io/app1:${IMAGE_TAG} \
          -n dev

        kubectl rollout status deployment/dev-app1 -n dev
