name: Build & Deploy DEV

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: app1

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build image
        run: |
          docker build -f docker/Dockerfile.app1 \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ github.run_number }}-dev .

      - name: Push image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ github.run_number }}-dev

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: AKSMM_group
          cluster-name: AKSMM

      - name: Deploy DEV
        run: |
          helm upgrade --install app1-dev helm-app1 \
            -n dev \
            -f helm-app1/values-dev.yaml \
            --set image.tag=${{ github.run_number }}-devm
