name: Promote to PROD

on:
  workflow_dispatch:
    inputs:
      uat_image_tag:
        description: "Tag UAT Ã  promouvoir (ex: uat-4)"
        required: true
      prod_image_tag:
        description: "Tag PROD Ã  crÃ©er (ex: prod-4)"
        required: true

jobs:
  promote-prod:
    runs-on: ubuntu-latest
    environment: prod   # ðŸ” approval obligatoire

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Promote image UAT â†’ PROD
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.uat_image_tag }}
          docker tag  ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.uat_image_tag }} \
                      ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.prod_image_tag }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.prod_image_tag }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: AKSMM_group
          cluster-name: AKSMM

      - name: Deploy PROD
        run: |
          helm upgrade --install app1-prod helm-app1 \
            -n prod \
            --create-namespace \
            -f helm-app1/values-prod.yaml \
            --set image.tag=${{ inputs.prod_image_tag }}

      # ðŸ”½ JOURNALISATION DES RELEASES PROD ðŸ”½

      - name: Save PROD release info
        run: |
          echo "## PROD RELEASE" >> releases.md
          echo "- Date (UTC): $(date -u)" >> releases.md
          echo "- Image:" >> releases.md
          kubectl get deployment app1-prod -n prod \
            -o jsonpath="{.spec.template.spec.containers[0].image}" >> releases.md
          echo "" >> releases.md

      - name: Commit release log
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add releases.md
          git commit -m "chore(prod): log release" || echo "No changes to commit"
          git push
