name: Promote to UAT

on:
  workflow_dispatch:
    inputs:
      dev_image_tag:
        description: "Tag DEV à promouvoir (ex: dev-4)"
        required: true
      uat_image_tag:
        description: "Tag UAT à créer (ex: uat-4)"
        required: true

jobs:
  promote-uat:
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Promote image DEV → UAT
        run: |
          docker pull ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.dev_image_tag }}
          docker tag  ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.dev_image_tag }} \
                      ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.uat_image_tag }}
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/app1:${{ inputs.uat_image_tag }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: AKSMM_group
          cluster-name: AKSMM

      - name: Deploy UAT
        run: |
          helm upgrade --install app1-uat helm-app1 \
            -n uat \
            -f helm-app1/values-uat.yaml \
            --set image.tag=${{ inputs.uat_image_tag }}
